profile = "azure-gpt5"

[model_providers.azure]
name = "Azure"
base_url = "https://ygjpe.openai.azure.com/openai/v1/"
wire_api = "responses"

[profiles.azure-gpt5]
model = "gpt-5"
model_provider = "azure"